spring:
  datasource:
    username: root
    password: 1234567800
    url: jdbc:mysql://47.109.34.96:3306/face?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlt:
    multipart:
      max-file-size :10MB


# 整合mybatis
mybatis:
  #  type-aliases-package: com.face.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9000

files:
  upload:
    path: /Users/bigbear/Desktop/files/



